### ISSUE TITLE
希望可以出一个教学视频比较容易懂

### ISSUE THREAD

**Issue by ZClee128** [Jinxiansen/SwiftServerDocument#2]
希望可以出一个教学视频比较容易懂，一直想学，在自学的路途中发现资料很少，文档参差不齐，如果能出个教学视频，对于我们自学的人来说也是福利，希望可以考虑考虑

**Comment by Jinxiansen** [comment]
录视频，有点困难...
鄙人讲话，口齿不清，语无伦次，难等大雅之堂，不敢录视频献丑。

不过我这里有一个比较完整的 Swift 服务端项目，你如果感兴趣的话可以了解一下：
https://github.com/Jinxiansen/SwiftServerSide-Vapor
